print('Exercício 0: Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.')
lista = list(range(2,21,2))
print('Somente os numeros pares: \n',lista)
print()
print('Exercício 1: Crie uma lista chamada numeros que contenha os números inteiros de 1 a 10 e imprima-a na tela.')
lista1 = list(range(1,11))
print('Lista simples:',lista1)
print()
print('Exercício 2: Acesse e imprima o terceiro elemento da lista numeros.')
print(' o terceiro elemento da lista simples é: ',lista1[2])
print()
print('Exercício 3: Adicione o número 9 à lista numeros e imprima a lista atualizada.')
lista2 = [1,2,3,4,5,6,7,8]
print('Lista original:',lista2)
lista2.append(9)
print('Lista atualizada:',lista2)
print()
print('Exercício 4: Remova o número 5 da lista numeros e imprima a lista resultante.')
listas = [1,2,3,4,5,6]
print ('Lista com 6 numeros: ',listas)
listas.pop(4)
print (' Foi retirado um numero da lista: ',listas)
print()
print('Exercício 5: Crie uma lista chamada carros contendo três nomes de carros diferentes. Em seguida, concatene essa lista com a lista numeros e imprima o resultado.')
carros = ['Fusca, TL, Chevett']
print(' Os melhores carros do mundo são estes; ',carros)
carros +=(3500.00,2000.00,3000.00)
print(' Os melhores carros do mundo são estes e seus preços; ',carros)
